"""Switched Lennard-Jones repulsion and dispersion, summed over every pair.

**What this term is for.**  `zbl.taper` cuts the screened-nuclear repulsion off
at 1.5 A, which is what let the water dimer bind at all -- and left the model
with no intermolecular wall whatsoever above that radius, and no dispersion
anywhere.  Measured: a 64-water box at ambient density read -7.6 kbar and the
equation-of-state crossing sat near 1250 kg/m**3 against an experimental 997.
Too dense, by a quarter, because nothing stopped the box contracting.  This is
the term that stops it.  It is also the only attraction in the force field that
is not electrostatic.

**Why it was retired, and what changed.**  Not because a 12-6 is wrong, but
because q-force's parameters make it enormous at the separations reactive
chemistry visits.  With `sigma_H = 1.96 A` and `r**-12` hardness, a pair at a
*bond length* is deep inside the core:

    pair  r (A)  what it is              12-6      ZBL
    H-H   0.777  the H2 bond length    504 eV    2.0 eV
    O-H   0.960  the O-H bond length   930 eV    5.4 eV
    O-O   1.210  the O2 bond length   1348 eV   11.6 eV

A fixed-topology force field never notices, because those pairs are always
excluded.  A reactive one does: a diabatic state that has *broken* a bond calls
its two atoms different molecules while they sit at the bond length, and pays
hundreds of eV for it.  Every attempt to strip that penalty made the repulsion
differ between diabatic states, and each failed differently -- stripping it from
the unreacted parent as well let the box fuse at 0.60 A; gating it on the
coupling left a 19 eV plateau across rxn_16's reaction path where a wall was
half-removed; and transition states with close non-bonded contacts came back
with EVB amplitudes of -72 to -108 eV.

Every one of those four descends from the same root: **a pair at a bond length
being charged hundreds of eV, and the charge depending on the topology.**
`lj.switch` removes the root rather than the symptoms.  The term is now 0.031 eV
at an O-H bond and 0.35 eV at O2's, three to four orders of magnitude down, and
at that size there is no penalty worth stripping -- so the **whole-system sum
carries no exclusions**.  That is the property that matters, and it is
structural rather than a tuning: with nothing excluded, this sum is the same
number for every diabatic state of every block, so it adds a common shift to
every EVB diagonal, and a common shift moves `np.linalg.eigh`'s eigenvalue by
exactly that constant while leaving the eigenvectors untouched.
It **cannot** produce a plateau, a spurious coupling amplitude, a pivot
dependence, or a discontinuity at the bimolecular cutoff -- not "does not",
cannot.  Each of the four failures lived in the degree of freedom the switch
removes, which is the same argument `forcefield/zbl.py` makes for itself.

The functions that carried those four attempts -- `reactive_exclusion_weights`,
`fixed_basis_weights`, `exclusion_correction`, `lost_exclusion_correction` --
are gone and are not coming back.

**What it costs.**  The same thing `zbl.taper` cost, and for the same reason.
fast-forces' `refine` solves against `E_QForce + E_nonbonded`, and this term is
now inside `E_nonbonded`, so **every `.jsonl` in every dataset has to be
regenerated by `fast-forces refit` after any change to `switch_radius` or
`switch_width`.**  See `production/density-300K/README.md` for what the refit
came to.

**The decomposition.**  LJ depends on the topology only through exclusions, and
exclusions are local to a molecule, so

    E_LJ(state) = sum_{i<j, far apart along the bonds} u_ij
                = sum_{i<j} u_ij  -  sum_{i<j, near along the bonds} u_ij

The first sum is this class, once for the whole system.  The second is a set of
ordinary per-template `exclusion` terms, which `ReactionSet.load` derives through
`forcefield/exclusions.py` and `QForce.compute_exclusion` evaluates on each
diabat's diagonal -- small, because the switch has already taken the term to
millielectronvolts at a bond length, and built from `pair_potential` below so
the two halves are the same function of the same numbers.

Units are ASE's -- sigma in Angstrom, epsilon in eV -- like every other term.
q-force states them in nm and kJ/mol, and `io/units.py` converts them once when
the `.jsonl` is read.
"""

import networkx as nx
import numpy as np

from DynamicTopology.forcefield.params import ForceFieldParams, active, resolve


# `EXCLUSION_DEPTH`, `CORE_FRACTION`, `SWITCH_RADIUS` and `SWITCH_WIDTH` are now
# fields of `params.ForceFieldParams` -- `exclusion_depth`, `core_fraction`,
# `switch_radius` and `switch_width` -- read through `params.resolve()` at
# call time; see that module for why.


def switch(
    r: np.ndarray, params: ForceFieldParams | None = None
) -> tuple[np.ndarray, np.ndarray]:
    """`g = 1 - 1/(1 + exp((r - rc)/w))`, the mirror image of `zbl.taper`.

    Returns `(g, dg/dr)`.  `g` runs from 0 well inside `switch_radius` to 1 well
    outside it, and `dg/dr = g (1 - g) / w`.

    It is the same functional form as `zbl.taper` reflected, and the same width,
    but **not its complement**: `switch_radius` is 2.2 A where `taper_radius` is
    1.5, so `switch(r) + taper(r)` is not 1 and the two terms leave a gap
    rather than handing straight over.  See `params.ForceFieldParams` for the
    measurement that forces this and for what lives in the gap.

    `params` defaults to the active set -- the dataset's, once a manifest has
    been loaded.  `r` is in Angstrom, as `switch_radius` and `switch_width` are.

    The exponent is clipped for the same reason `zbl.taper` clips it: this is
    evaluated over every pair in the box, including ones half a cell apart, and
    an unclipped `exp` overflows to `inf` and turns `g (1 - g)` into `0 * inf`.
    """
    ff = resolve(params)
    z = np.clip((r - ff.switch_radius) / ff.switch_width, -500.0, 500.0)
    f = 1.0 / (1.0 + np.exp(z))
    return 1.0 - f, f * (1.0 - f) / ff.switch_width


def pair_potential(
    r: np.ndarray,
    sigma: np.ndarray,
    eps: np.ndarray,
    params: ForceFieldParams | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Switched 12-6 and its radial derivative, `(u, du/dr)`.

    This is the potential the force field evaluates, not the textbook 12-6: it
    is multiplied by `switch`, so it is off inside `switch_radius` and on
    outside it.  See the module docstring for why, and
    `params.ForceFieldParams.switch_radius` for where the boundary sits relative
    to `zbl`'s taper radius.

    `r` and `sigma` in Angstrom, because `switch` fixes the length unit; `u`
    comes back in the unit of `eps`, which is eV everywhere it is called.

    Every caller goes through here so the forms can never drift apart -- and
    they must not, because the near-neighbour half of the sum is cancelled by
    `exclusion` terms built from this same form.

    **Below `core_fraction * sigma` the potential continues along its own
    tangent instead of as `r**-12`, and this is not cosmetic.**  The
    decomposition `E = sum_all_pairs - sum_near_pairs` evaluates every *bonded*
    pair in both sums, at a separation where 12-6 is enormous.  At equilibrium
    that is merely ugly -- 843 eV cancelling to zero on an H2 template, with
    thirteen digits to spare.  On a hot trajectory it is fatal: an H2 bond
    compressed to 0.3 A puts 1e8 eV into both sums, 0.2 A puts in 1e10, and
    0.024 A puts in 1e21.  Measured on the 3000 K probe, the two sums reached
    1e21 by step 143 and their difference -- the physical energy, of order 1e2
    -- came back quantized to 2**22 eV.  The forces went with it and the box
    heated to 1e16 K.

    Linear continuation bounds what a compressed bond can contribute (about 4500
    eV at 0.3 A rather than 8e7, and 5700 eV at 0.024 A rather than 1e21) while
    staying C1, so the cancellation keeps its precision and the gradient stays
    the gradient.  Because both halves come through here, the switch cancels
    exactly on any pair that is excluded, which is every pair it can reach.
    """
    ff = resolve(params)
    core = ff.core_fraction * sigma
    # Evaluate the true form at max(r, core) -- so the branch below never sees
    # the divergence at all -- then extrapolate back along the tangent.
    r_eval = np.maximum(r, core)
    sr6 = (sigma / r_eval) ** 6
    sr12 = sr6 * sr6
    u = 4.0 * eps * (sr12 - sr6)
    du_dr = -(24.0 * eps / r_eval) * (2.0 * sr12 - sr6)
    # `du_dr` needs no branch: evaluated at `core` it is already the tangent's
    # constant slope, which is exactly the derivative of the linear piece.
    u = np.where(r < core, u + du_dr * (r - core), u)

    # Product rule, applied here rather than in `__call__` for the reason
    # `zbl.pair_potential` gives: the forces, the virial and
    # fast-forces' `refine`'s curvatures all differentiate whatever this
    # function returns, so the switch and its derivative have to travel
    # together.
    #
    # The linear continuation above is what makes this well defined at small
    # `r`.  `g` goes to zero there while an unclamped `r**-12` goes to 1e21, and
    # `0 * 1e21` is not zero in floating point -- it is 1e21 times a denormal
    # and then whatever the compiler feels like.  Bounded at ~5700 eV, the
    # product is a clean underflow to zero.
    g, dg_dr = switch(r, ff)
    return g * u, g * du_dr + dg_dr * u


def near_pairs(graph: nx.Graph, depth: int | None = None) -> set[tuple[int, int]]:
    """Node pairs within `depth` bonds of each other in `graph`, as `(i, j)`, i < j.

    `depth` defaults to the active `exclusion_depth`, resolved here rather than
    in the signature so that a manifest loaded after import is still honoured.
    """
    if depth is None:
        depth = active().exclusion_depth
    pairs: set[tuple[int, int]] = set()
    for node in graph:
        for other, distance in nx.single_source_shortest_path_length(
            graph, node, cutoff=depth
        ).items():
            if distance == 0 or other <= node:
                continue
            pairs.add((node, other))
    return pairs


class LennardJones:
    """12-6 with geometric combining, over all pairs.

    Two index spaces meet here, as in `ACKS2`, and confusing them is silent:
    the per-atom parameters arrive in *term order* -- the order the
    `lennardjones` terms were collected -- while `pos` and the returned forces
    are in *global* atom order.  `indices[k]` is the global index of the k-th
    term.  Everything is built in term order and the forces are scattered back
    at the very end.

    Combining is geometric in both parameters, matching q-force's
    `A=sqrt(A1*A2); B=sqrt(B1*B2)` -- *not* Lorentz-Berthelot.  Using the
    arithmetic mean for sigma here would silently disagree with
    `compute_exclusion`, and the disagreement would show up only as templates
    no longer reproducing their own energies.
    """

    def __call__(
        self, pos: np.ndarray, pbc: np.ndarray, cell: np.ndarray, term_dict: dict
    ) -> tuple[float, np.ndarray, np.ndarray]:
        params = term_dict.get("lennardjones")
        if params is None:
            raise KeyError(
                "No `lennardjones` parameters set. Every atom needs a sigma and "
                "an epsilon, or the system has no Pauli repulsion and molecules "
                "will interpenetrate."
            )
        indices = params["atoms"][:, 0]
        sigma = params["kwargs"]["sigma"]
        eps = params["kwargs"]["eps"]

        vecs = pos[:, None, :] - pos[None, :, :]
        if np.any(pbc):
            F = vecs @ np.linalg.inv(cell)
            vecs = vecs - (pbc * np.floor(F + 0.5)) @ cell

        # Both axes in term order, so the parameter vectors line up with them.
        sub = np.ix_(indices, indices)
        vecs = vecs[sub]
        rij = np.sqrt(np.sum(vecs * vecs, -1))

        diag = np.diag_indices(len(indices))
        r = rij.copy()
        r[diag] = 1.0  # excluded below; only keeps the division finite

        sig = np.sqrt(sigma[:, None] * sigma[None, :])
        epsilon = np.sqrt(eps[:, None] * eps[None, :])

        e, du_dr = pair_potential(r, sig, epsilon)
        e[diag] = 0.0
        du_dr[diag] = 0.0
        e_tot = 0.5 * float(np.sum(e))
        # The 0.5 above cancels because both (i, j) and (j, i) contribute to
        # dE/d(pos_i), which is the same convention `ACKS2.compute_coulomb` uses.
        nij = vecs / r[:, :, None]
        f_tot = -np.sum(du_dr[:, :, None] * nij, axis=1)

        forces = np.zeros_like(pos)
        forces[indices] = f_tot

        # Virial, exactly as `ZBL.__call__` builds it: under a homogeneous
        # strain `v -> (I + e) v`, so `dr/de_ab = v_a v_b / r`.  The 0.5 is the
        # energy's and does *not* cancel here -- `v_a v_b` is even under swapping
        # i and j, unlike the force's `nij`.
        virial = 0.5 * np.einsum("ij,ija,ijb->ab", du_dr / r, vecs, vecs)
        return e_tot, forces, virial
