"""Switched Lennard-Jones repulsion and dispersion, summed over every pair.

**What this term is for.**  `zbl.taper` cuts the screened-nuclear repulsion off
at 1.5 A, which is what let the water dimer bind at all -- and left the model
with no intermolecular wall whatsoever above that radius, and no dispersion
anywhere.  Measured: a 64-water box at ambient density read -7.6 kbar and the
equation-of-state crossing sat near 1250 kg/m**3 against an experimental 997.
Too dense, by a quarter, because nothing stopped the box contracting.  This is
the term that stops it.  It is also the only attraction in the force field that
is not electrostatic.

**Why it was retired, and what changed.**  Not because a 12-6 is wrong, but
because q-force's parameters make it enormous at the separations reactive
chemistry visits.  With `sigma_H = 1.96 A` and `r**-12` hardness, a pair at a
*bond length* is deep inside the core:

    pair  r (A)  what it is              12-6      ZBL
    H-H   0.777  the H2 bond length    504 eV    2.0 eV
    O-H   0.960  the O-H bond length   930 eV    5.4 eV
    O-O   1.210  the O2 bond length   1348 eV   11.6 eV

A fixed-topology force field never notices, because those pairs are always
excluded.  A reactive one does: a diabatic state that has *broken* a bond calls
its two atoms different molecules while they sit at the bond length, and pays
hundreds of eV for it.  Every attempt to strip that penalty made the repulsion
differ between diabatic states, and each failed differently -- stripping it from
the unreacted parent as well let the box fuse at 0.60 A; gating it on the
coupling left a 19 eV plateau across rxn_16's reaction path where a wall was
half-removed; and transition states with close non-bonded contacts came back
with EVB amplitudes of -72 to -108 eV.

Every one of those four descends from the same root: **a pair at a bond length
being charged hundreds of eV, and the charge depending on the topology.**
`lj.switch` removes the root rather than the symptoms, and `pair_potential`'s
soft core bounds what is left.  The term is now 0.0024 eV at an O-H bond and
0.035 eV at O2's, four to five orders of magnitude down, and
at that size there is no penalty worth stripping -- so the **whole-system sum
carries no exclusions**.  That is the property that matters, and it is
structural rather than a tuning: with nothing excluded, this sum is the same
number for every diabatic state of every block, so it adds a common shift to
every EVB diagonal, and a common shift moves `np.linalg.eigh`'s eigenvalue by
exactly that constant while leaving the eigenvectors untouched.
It **cannot** produce a plateau, a spurious coupling amplitude, a pivot
dependence, or a discontinuity at the bimolecular cutoff -- not "does not",
cannot.  Each of the four failures lived in the degree of freedom the switch
removes, which is the same argument `forcefield/zbl.py` makes for itself.

The functions that carried those four attempts -- `reactive_exclusion_weights`,
`fixed_basis_weights`, `exclusion_correction`, `lost_exclusion_correction` --
are gone and are not coming back.

**What it costs.**  The same thing `zbl.taper` cost, and for the same reason.
fast-forces' `refine` solves against `E_QForce + E_nonbonded`, and this term is
now inside `E_nonbonded`, so **every `.jsonl` in every dataset has to be
regenerated by `fast-forces refit` after any change to `switch_radius` or
`switch_width`.**  See `production/density-300K/README.md` for what the refit
came to.

**The decomposition.**  LJ depends on the topology only through exclusions, and
exclusions are local to a molecule, so

    E_LJ(state) = sum_{i<j, far apart along the bonds} u_ij
                = sum_{i<j} u_ij  -  sum_{i<j, near along the bonds} u_ij

The first sum is this class, once for the whole system.  The second is a set of
ordinary per-template `exclusion` terms, which `ReactionSet.load` derives through
`forcefield/exclusions.py` and `QForce.compute_exclusion` evaluates on each
diabat's diagonal -- small, because the switch has already taken the term to
millielectronvolts at a bond length, and built from `pair_potential` below so
the two halves are the same function of the same numbers.

Units are ASE's -- sigma in Angstrom, epsilon in eV -- like every other term,
and as the `.jsonl` stores them.  q-force states them in nm and kJ/mol, and
`io/units.py` converts them once, when fast-forces imports its XML.
"""

import networkx as nx
import numpy as np

from DynamicTopology.forcefield.ewald import contract_pairs
from DynamicTopology.forcefield.params import ForceFieldParams, active, resolve
from DynamicTopology.forcefield.pointcharge import pair_gradients, subset


# `EXCLUSION_DEPTH`, `SWITCH_RADIUS` and `SWITCH_WIDTH` are now fields of
# `params.ForceFieldParams` -- `exclusion_depth`, `switch_radius` and
# `switch_width` -- read through `params.resolve()` at call time, as is the
# soft-core constant `soft_core`; see that module for why.


def switch(
    r: np.ndarray, params: ForceFieldParams | None = None
) -> tuple[np.ndarray, np.ndarray]:
    """`g = 1 - 1/(1 + exp((r - rc)/w))`, the mirror image of `zbl.taper`.

    Returns `(g, dg/dr)`.  `g` runs from 0 well inside `switch_radius` to 1 well
    outside it, and `dg/dr = g (1 - g) / w`.

    It is the same functional form as `zbl.taper` reflected, and the same width,
    but **not its complement**: `switch_radius` is 2.2 A where `taper_radius` is
    1.5, so `switch(r) + taper(r)` is not 1 and the two terms leave a gap
    rather than handing straight over.  See `params.ForceFieldParams` for the
    measurement that forces this and for what lives in the gap.

    `params` defaults to the active set -- the dataset's, once a manifest has
    been loaded.  `r` is in Angstrom, as `switch_radius` and `switch_width` are.

    The exponent is clipped for the same reason `zbl.taper` clips it: this is
    evaluated over every pair in the box, including ones half a cell apart, and
    an unclipped `exp` overflows to `inf` and turns `g (1 - g)` into `0 * inf`.
    """
    ff = resolve(params)
    z = np.clip((r - ff.switch_radius) / ff.switch_width, -500.0, 500.0)
    f = 1.0 / (1.0 + np.exp(z))
    return 1.0 - f, f * (1.0 - f) / ff.switch_width


def pair_potential(
    r: np.ndarray,
    sigma: np.ndarray,
    eps: np.ndarray,
    params: ForceFieldParams | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Switched soft-core 12-6 and its radial derivative, `(u, du/dr)`.

    This is the potential the force field evaluates, not the textbook 12-6: it
    is multiplied by `switch`, so it is off inside `switch_radius` and on
    outside it.  See the module docstring for why, and
    `params.ForceFieldParams.switch_radius` for where the boundary sits relative
    to `zbl`'s taper radius.

    `r` and `sigma` in Angstrom, because `switch` fixes the length unit; `u`
    comes back in the unit of `eps`, which is eV everywhere it is called.

    Every caller goes through here so the forms can never drift apart -- and
    they must not, because the near-neighbour half of the sum is cancelled by
    `exclusion` terms built from this same form.

    **The 12-6 is soft-cored, and this is not cosmetic.**  With
    `s = c + (r/sigma)**6` and `c = soft_core`,

        u = 4 eps [ s**-2 - s**-1 ]

    which is the textbook 12-6 at `c = 0` and, for `c > 0`, finite everywhere:
    `u(0) = 4 eps (1/c**2 - 1/c)`, 39600 eps at the default 0.01.  The
    decomposition `E = sum_all_pairs - sum_near_pairs` evaluates every *bonded*
    pair in both sums, at a separation where bare 12-6 is enormous.  At
    equilibrium that is merely ugly -- 843 eV cancelling to zero on an H2
    template, with thirteen digits to spare.  On a hot trajectory it is fatal:
    an H2 bond compressed to 0.3 A puts 1e8 eV into both sums, 0.2 A puts in
    1e10, and 0.024 A puts in 1e21.  Measured on the 3000 K probe, the two sums
    reached 1e21 by step 143 and their difference -- the physical energy, of
    order 1e2 -- came back quantized to 2**22 eV.  The forces went with it and
    the box heated to 1e16 K.

    The soft core bounds what a compressed bond can contribute -- under 300 eV
    for the heaviest pair the datasets carry, at any separation -- while being
    smooth rather than merely C1, so the cancellation keeps its precision and
    the gradient stays the gradient.  Where the term does physical work it is
    barely touched: the minimum is still at `s = 2`, so the well depth is
    exactly `eps` and only its position moves, inward by `(1 - c/2)**(1/6)`,
    0.08%; the zero crossing, at `s = 1`, moves inward by 0.17%.  Because both halves come through here, the
    switch cancels exactly on any pair that is excluded, which is every pair it
    can reach.

    A pair with `sigma = 0` has no 12-6 at all, as it had under the bare form,
    and is masked rather than divided by.
    """
    ff = resolve(params)
    has_lj = sigma != 0.0
    x6 = (r / np.where(has_lj, sigma, 1.0)) ** 6
    inv_s = 1.0 / (ff.soft_core + x6)
    inv_s2 = inv_s * inv_s
    u = np.where(has_lj, 4.0 * eps * (inv_s2 - inv_s), 0.0)
    # ds/dr = 6 x6 / r; the r is kept out of the denominator so a pair at
    # exact contact, which the soft core now makes finite, stays finite.
    ds_dr = 6.0 * r**5 / np.where(has_lj, sigma, 1.0) ** 6
    du_dr = np.where(has_lj, 4.0 * eps * (inv_s2 - 2.0 * inv_s2 * inv_s) * ds_dr, 0.0)

    # Product rule, applied here rather than in `__call__` for the reason
    # `zbl.pair_potential` gives: the forces, the virial and
    # fast-forces' `refine`'s curvatures all differentiate whatever this
    # function returns, so the switch and its derivative have to travel
    # together.
    #
    # The soft core above is what makes this well defined at small `r`.  `g`
    # goes to zero there while a bare `r**-12` goes to 1e21, and `0 * 1e21` is
    # not zero in floating point -- it is 1e21 times a denormal and then
    # whatever the compiler feels like.  Bounded by `4 eps / c**2`, the product
    # is a clean underflow to zero.
    g, dg_dr = switch(r, ff)
    return g * u, g * du_dr + dg_dr * u


def near_pairs(graph: nx.Graph, depth: int | None = None) -> set[tuple[int, int]]:
    """Node pairs within `depth` bonds of each other in `graph`, as `(i, j)`, i < j.

    `depth` defaults to the active `exclusion_depth`, resolved here rather than
    in the signature so that a manifest loaded after import is still honoured.
    """
    if depth is None:
        depth = active().exclusion_depth
    pairs: set[tuple[int, int]] = set()
    for node in graph:
        for other, distance in nx.single_source_shortest_path_length(
            graph, node, cutoff=depth
        ).items():
            if distance == 0 or other <= node:
                continue
            pairs.add((node, other))
    return pairs


class LennardJones:
    """12-6 with geometric combining, over all pairs.

    Two index spaces meet here, as in `ACKS2`, and confusing them is silent:
    the per-atom parameters arrive in *term order* -- the order the
    `lennardjones` terms were collected -- while `pos` and the returned forces
    are in *global* atom order.  `indices[k]` is the global index of the k-th
    term.  Everything is built in term order and the forces are scattered back
    at the very end.

    Combining is geometric in both parameters, matching q-force's
    `A=sqrt(A1*A2); B=sqrt(B1*B2)` -- *not* Lorentz-Berthelot.  Using the
    arithmetic mean for sigma here would silently disagree with
    `compute_exclusion`, and the disagreement would show up only as templates
    no longer reproducing their own energies.
    """

    def __call__(
        self,
        pos: np.ndarray,
        pbc: np.ndarray,
        cell: np.ndarray,
        term_dict: dict,
        displacements=None,
    ) -> tuple[float, np.ndarray, np.ndarray]:
        """Energy, forces and virial; `displacements` is `pointcharge.geometry`
        over every atom, if the caller already has it."""
        params = term_dict.get("lennardjones")
        if params is None:
            raise KeyError(
                "No `lennardjones` parameters set. Every atom needs a sigma and "
                "an epsilon, or the system has no Pauli repulsion and molecules "
                "will interpenetrate."
            )
        indices = params["atoms"][:, 0]
        sigma = params["kwargs"]["sigma"]
        eps = params["kwargs"]["eps"]

        # Both axes in term order, so the parameter vectors line up with them.
        vecs, rij = subset(displacements, indices, pos, pbc, cell)

        ff = active()
        if ff.lj_cutoff is not None:
            return self._cut(pos, pbc, cell, indices, sigma, eps, vecs, rij, ff)

        diag = np.diag_indices(len(indices))
        r = rij.copy()
        r[diag] = 1.0  # excluded below; only keeps the division finite

        sig = np.sqrt(sigma[:, None] * sigma[None, :])
        epsilon = np.sqrt(eps[:, None] * eps[None, :])

        e, du_dr = pair_potential(r, sig, epsilon)
        e[diag] = 0.0
        du_dr[diag] = 0.0
        e_tot = 0.5 * float(np.sum(e))
        # `E = sum_ij W_ij u(r_ij)` with `W = 1/2`, which is the form
        # `contract_pairs` differentiates: it doubles the force for the (i, j) /
        # (j, i) pair, cancelling the 0.5, and leaves the virial's -- even under
        # the swap -- in place.  Under a homogeneous strain `v -> (I + e) v`,
        # so `dr/de_ab = v_a v_b / r`, as `ZBL.__call__` has it.
        dE_dr, virial = contract_pairs(0.5 * du_dr, vecs, r)

        forces = np.zeros_like(pos)
        forces[indices] = -dE_dr
        return e_tot, forces, virial

    def _cut(self, pos, pbc, cell, indices, sigma, eps, vecs, rij, ff):
        """The 12-6 within `lj_cutoff`, switched off smoothly, plus its tail."""
        rc = ff.lj_cutoff
        ron = rc - ff.lj_cutoff_width
        periodic = bool(np.all(pbc))
        if np.any(pbc):
            widths = 1.0 / np.linalg.norm(np.linalg.inv(np.asarray(cell)), axis=0)
            if rc > 0.5 * widths[np.asarray(pbc, dtype=bool)].min() + 1e-12:
                raise ValueError(
                    f"lj_cutoff {rc} A exceeds half the cell's perpendicular "
                    f"width ({0.5 * widths.min():.3f} A): the minimum image would "
                    "miss pairs inside it"
                )
        i, j = np.nonzero(np.triu(rij < rc, 1))
        r = rij[i, j]
        u, du_dr = pair_potential(
            r, np.sqrt(sigma[i] * sigma[j]), np.sqrt(eps[i] * eps[j])
        )
        s, ds_dr = cutoff_switch(r, ron, rc)
        energy = float(np.sum(u * s))
        f_pair, virial = pair_gradients(i, j, du_dr * s + u * ds_dr, vecs, rij)
        forces = np.zeros_like(pos)
        forces[indices] = f_pair
        if periodic:
            volume = abs(np.linalg.det(np.asarray(cell)))
            tail = _tail(sigma, eps, ron, rc, ff) / volume
            # `E_tail = T / V` and a strain scales `V` by `1 + tr e`.
            energy += tail
            virial = virial - tail * np.eye(3)
        return energy, forces, virial


def cutoff_switch(r: np.ndarray, ron: float, rc: float):
    """CHARMM's energy switch, 1 inside `ron`, 0 at `rc`, and its derivative.

    `S = (rc^2 - r^2)^2 (rc^2 + 2 r^2 - 3 ron^2) / (rc^2 - ron^2)^3` between
    the two: continuous with its first derivative at both ends, so the energy
    and the forces are.
    """
    r2 = r * r
    denom = (rc * rc - ron * ron) ** 3
    inner, outer = r <= ron, r >= rc
    s = (rc * rc - r2) ** 2 * (rc * rc + 2 * r2 - 3 * ron * ron) / denom
    ds = 12 * r * (rc * rc - r2) * (ron * ron - r2) / denom
    return (
        np.where(inner, 1.0, np.where(outer, 0.0, s)),
        np.where(inner | outer, 0.0, ds),
    )


_TAILS: dict = {}


def _tail(sigma, eps, ron, rc, ff) -> float:
    """`V E_tail = 2 pi sum_ab N_a N_b int r^2 u_ab(r) (1 - S(r)) dr`.

    The 12-6 a uniform fluid puts beyond the switch, over every ordered pair of
    atoms, by type: the integrand is `pair_potential` itself, soft core and
    all, so the correction is of the term evaluated rather than of the
    textbook one.  Cached on the composition and the parameters, since a fixed
    set of atoms in any cell has the same `T`.
    """
    types, counts = np.unique(np.stack([sigma, eps], axis=1), axis=0, return_counts=True)
    key = (types.tobytes(), counts.tobytes(), ron, rc, ff)
    if key not in _TAILS:
        from scipy.integrate import quad

        total = 0.0
        for a, (sa, ea) in enumerate(types):
            for b, (sb, eb) in enumerate(types):
                sig, ep = np.sqrt(sa * sb), np.sqrt(ea * eb)
                if sig == 0.0 or ep == 0.0:
                    continue

                def integrand(r, inside):
                    u = pair_potential(np.array([r]), sig, ep, ff)[0][0]
                    weight = 1.0 - cutoff_switch(np.array([r]), ron, rc)[0][0]
                    return r * r * u * (weight if inside else 1.0)

                inner = quad(integrand, ron, rc, args=(True,), epsabs=0, epsrel=1e-12)[0]
                outer = quad(integrand, rc, np.inf, args=(False,), epsabs=0, epsrel=1e-12)[0]
                total += counts[a] * counts[b] * (inner + outer)
        _TAILS[key] = 2.0 * np.pi * total
    return _TAILS[key]
